### ISSUE TITLE
异步加载组件问题

### ISSUE THREAD

**Issue by 303182519** [iversong/fis3-vue-scaffold#1]
兄弟，你有没有遇到过vue-router异步加载组件的时候Failed to mount component: template or render function not defined. 报错。安装组件失败的

**Comment by iversong** [comment]
@303182519  Vue的npm包默认是**运行时**构建，运行时构建不包含模板编译器，因此不支持 template 选项，只能用 render 选项，如果在非单文件组件中使用template模板选项就会组件报错，你可以换用.vue的单文件组件尝试下。
[独立构建-vs-运行时构建](http://cn.vuejs.org/v2/guide/installation.html#独立构建-vs-运行时构建)

**Comment by 303182519** [comment]
其实单文件的.vue,我已经用fis做了编译了，路由的组件，假如我是同步打开在一起的话，就没有问题，改成异步就出问题了

**Comment by 303182519** [comment]
//路由的代码

```
var foo = function foo(resolve) {
    return require(['components/foo.vue'], resolve);
  }; 
  
  //引入vue、vue-router和根组件app.vue
  
  
  _vue2.default.use(_vueRouter2.default);
  
  var router = new _vueRouter2.default({
    routes: [{ path: '/foo', component: foo }, { path: '/bar', component: _bar2.default }]
  });
```

=============================================

```
//foo.vue组件
define('components/foo.vue', function(require, exports, module) {

  "use strict";
  
  Object.defineProperty(exports, "__esModule", {
  	value: true
  });
  //
  //
  //
  //
  
  exports.default = {
  	data: function data() {
  		return {
  			aa: 666
  		};
  	}
  };
  var __vue__options__;
  if(exports && exports.__esModule && exports.default){
    __vue__options__ = exports.default;
  }else{
    __vue__options__ = module.exports;
  }
  __vue__options__.render =function render () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_vm._v(_vm._s(_vm.aa))])}
  __vue__options__.staticRenderFns =[]
  

});
```

**Comment by iversong** [comment]
@303182519 我在Vue1.x下尝试是没问题的，如果你使用的是vue2.x，建议你查看下对应的.vue单文件编译插件，并且异步组件使用Vue.component注册下代替你的`//路由的代码
var foo = function foo(resolve) {
return require(['components/foo.vue'], resolve);
};`
[vue2.x异步组件](http://cn.vuejs.org/v2/guide/components.html#异步组件)
